import { Posture } from '@common/character';

// Constants for timing, common to front-end and back-end.
export const COMBAT_POSTURE_TIMEOUT_MS = 10000;
export const COMBAT_START_ANNOUNCEMENT_DELAY_MS = 3000;
export const COMBAT_POSTURE_COUNTDOWN_START_DELAY_MS = 3000;

export const COMBAT_START_POPUP_DISPLAY_DURATION_MS = 3000;
export const COMBAT_END_POPUP_DISPLAY_DURATION_MS = 4000;

export const POSTURE_RESULT_DISPLAY_DURATION_MS = 3000;
export const ROUND_PHASE_BUFFER_MS = 1000;
export const DICE_ROLL_DURATION_MS = 3000;
export const DICE_RESULT_DISPLAY_DURATION_MS = 4000;
export const DAMAGE_DISPLAY_DURATION_MS = 4000;
export const FIGHTER_ADVANCE_DURATION_MS = 1250;
export const FIGHTER_HOLD_DURATION_MS = 500;
export const FIGHTER_RETREAT_DURATION_MS = 1250;
export const STATUS_BUFFER_DURATION_MS = 3000;
export const NEXT_ROUND_ANNOUNCEMENT_DURATION_MS = 3000;

export const COMBAT_ROUND_DELAY_MS =
    POSTURE_RESULT_DISPLAY_DURATION_MS +
    ROUND_PHASE_BUFFER_MS +
    DICE_ROLL_DURATION_MS +
    DICE_RESULT_DISPLAY_DURATION_MS +
    ROUND_PHASE_BUFFER_MS +
    DAMAGE_DISPLAY_DURATION_MS +
    ROUND_PHASE_BUFFER_MS +
    FIGHTER_ADVANCE_DURATION_MS +
    FIGHTER_HOLD_DURATION_MS +
    FIGHTER_RETREAT_DURATION_MS +
    ROUND_PHASE_BUFFER_MS +
    FIGHTER_ADVANCE_DURATION_MS +
    FIGHTER_HOLD_DURATION_MS +
    FIGHTER_RETREAT_DURATION_MS +
    ROUND_PHASE_BUFFER_MS +
    STATUS_BUFFER_DURATION_MS +
    NEXT_ROUND_ANNOUNCEMENT_DURATION_MS;

export const COMBAT_ANIMATION_SPEED_MULTIPLIER = 0.6;
export const COMBAT_END_SEQUENCE_ROUND_BUFFER_COUNT = 3;
export const COMBAT_POST_ROUND_END_SEQUENCE_DELAY_MS = Math.round(
    (
        DICE_ROLL_DURATION_MS +
        DICE_RESULT_DISPLAY_DURATION_MS +
        (ROUND_PHASE_BUFFER_MS * COMBAT_END_SEQUENCE_ROUND_BUFFER_COUNT) +
        ((FIGHTER_ADVANCE_DURATION_MS + FIGHTER_HOLD_DURATION_MS + FIGHTER_RETREAT_DURATION_MS) * 2) +
        DAMAGE_DISPLAY_DURATION_MS
    ) * COMBAT_ANIMATION_SPEED_MULTIPLIER,
);
export const COMBAT_POST_DEATH_RESUME_DELAY_MS =
    COMBAT_POST_ROUND_END_SEQUENCE_DELAY_MS + COMBAT_END_POPUP_DISPLAY_DURATION_MS;
export const COMBAT_POST_ABANDON_RESUME_DELAY_MS = COMBAT_END_POPUP_DISPLAY_DURATION_MS;

export const COUNTDOWN_TICK_MS = 1000;
export const DEFAULT_POSTURE: Posture = { type: null, bonus: 0 };