import { CommonModule } from '@angular/common';
import { AfterViewChecked, Component, ElementRef, Input, OnChanges, OnDestroy, OnInit, SimpleChanges, ViewChild } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ChatService } from '@app/services/chat/chat.service';
import { ChatMessage } from '@common/chat-message';
import { Subscription } from 'rxjs';

const SCROLL_THRESHOLD = 75; // Pixels from the bottom to consider as "near bottom"

@Component({
    selector: 'app-chat',
    standalone: true,
    imports: [CommonModule, FormsModule],
    templateUrl: './chat.component.html',
    styleUrl: './chat.component.scss',
})
export class ChatComponentComponent implements OnInit, OnDestroy, OnChanges, AfterViewChecked {
    @Input() lobbyId: string = 'lobby';
    @Input() playerName: string = '';
    @Input() hasAbandoned: boolean = false;

    @ViewChild('messagesContainer') private messagesContainer!: ElementRef<HTMLDivElement>;

    draftMessage = '';
    messages: ChatMessage[] = [];
    isNearBottom = true;

    private messagesSub?: Subscription;
    private shouldScroll = false;
    private lastMessageCount = 0;

    constructor(private readonly chatService: ChatService) {}

    ngOnInit(): void {
        this.subscribeToMessages();
    }

    ngOnChanges(changes: SimpleChanges): void {
        if (changes.lobbyId && this.lobbyId) {
            this.subscribeToMessages();
        }
    }

    // Function generated by AI GPT-5.1
    // Automatically scrolls to the bottom of the chat after each update if the user is already at the bottom.
    ngAfterViewChecked(): void {
        if (this.shouldScroll && this.isNearBottom) {
            this.shouldScroll = false;
            this.scrollToBottom();
        }
    }

    ngOnDestroy(): void {
        this.messagesSub?.unsubscribe();
    }

    get displayName(): string {
        return this.playerName?.trim() || 'Joueur';
    }

    get canSend(): boolean {
        return Boolean(!this.hasAbandoned && this.lobbyId.trim() && this.draftMessage.trim().length > 0);
    }

    sendMessage(): void {
        if (!this.canSend) return;
        const message = this.draftMessage.trim();
        this.draftMessage = '';
        this.shouldScroll = true;
        this.isNearBottom = true;
        this.chatService.sendMessage(this.lobbyId, this.displayName, message);
    }

    private subscribeToMessages(): void {
        const lobbyId = this.lobbyId?.trim();
        if (!lobbyId) return;

        this.messagesSub = this.chatService.roomMessages$(lobbyId).subscribe((msgs) => {
            if (msgs.length > this.lastMessageCount) {
                this.shouldScroll = true;
            }
            this.lastMessageCount = msgs.length;
            this.messages = msgs;
        });
    }

    // Function generated by AI GPT-5.1
    // Detects user scroll events to update their position in the chat.
    onScroll(): void {
        this.updateScrollPosition();
    }

    // Function generated by AI GPT-5.1
    // Immediately scrolls to the bottom when the user clicks the scroll button.
    scrollToBottomClicked(): void {
        this.scrollToBottom();
        this.isNearBottom = true;
    }

    // Function generated by AI GPT-5.1
    // Calculates if the user is near the bottom of the chat to determine if automatic scrolling should occur.
    private updateScrollPosition(): void {
        if (!this.messagesContainer?.nativeElement) return;
        const container = this.messagesContainer.nativeElement;
        const distanceFromBottom = container.scrollHeight - (container.scrollTop + container.clientHeight);
        this.isNearBottom = distanceFromBottom < SCROLL_THRESHOLD;
    }

    // Function generated by AI GPT-5.1
    // Instantly scrolls the message container to the bottom to display the latest message.
    private scrollToBottom(): void {
        if (this.messagesContainer?.nativeElement) {
            const container = this.messagesContainer.nativeElement;
            container.scrollTop = container.scrollHeight;
        }
    }
}
