import { Injectable } from '@angular/core';
import { Vec2 } from '@common/vec2';
import { Player } from '@common/player';
import { OBJECT_PLACEMENT_TOOL, TILE_TOOLS } from '@app/constants/map-setup-page-constant';
import { TileRenderParams, RenderBoardConfig, TileColorSet, TileDepthParams } from '@app/interfaces/isometric-interfaces';

import {
  TILE_RATIO,
  TILE_THICKNESS,
  TILE_LINE_WIDTH,
  MIN_TILE_W,
  AUTO_ZOOM_FALLBACK,
  STROKE_COLOR,
  RENDER_CONSTANTS,
  TILE_COLORS,
  DEFAULT_COLOR,
  NAV_KEY_MARGIN,
  NAV_KEY_OFFSET_EXTRA,
} from '@app/constants/isometric.constants';

@Injectable({
  providedIn: 'root',
})
export class IsometricViewService {
  private imageCache: Map<string, HTMLImageElement> = new Map();
  private players: Player[] = [];
  private playerPositions: Record<string, Vec2> = {};

  private getImage(src: string): HTMLImageElement | null {
    if (!src) return null;
    if (this.imageCache.has(src)) {
      return this.imageCache.get(src) ?? null;
    }
    const img = new Image();
    img.src = src;
    this.imageCache.set(src, img);
    return img;
  }

  private buildPolygonPath(ctx: CanvasRenderingContext2D, points: Vec2[]): void {
    ctx.beginPath();
    ctx.moveTo(points[0].x, points[0].y);
    for (let i = 1; i < points.length; i++) {
      ctx.lineTo(points[i].x, points[i].y);
    }
    ctx.closePath();
  }


  renderBoard(config: RenderBoardConfig): void {
    const { ctx, width, height, grid, players, playerPositions, camera, needsRecenter, onRecenter } = config;
    if (!grid?.length || !grid[0]?.length) return;
    this.players = players;
    this.playerPositions = playerPositions;

    const totalRows = grid.length;
    const totalColumns = grid[0].length;

    const fitTileW = (2 * width) / (totalColumns + totalRows);
    const tileW = Math.max(fitTileW, MIN_TILE_W);
    const tileH = tileW / TILE_RATIO;

    if (needsRecenter) {
      camera.zoom = fitTileW >= MIN_TILE_W ? 1 : fitTileW / MIN_TILE_W;
      camera.zoom = Math.max(camera.zoom, AUTO_ZOOM_FALLBACK);
      camera.x = 0;
      camera.y = 0;
      onRecenter(camera.zoom, camera.x, camera.y);
    }

    ctx.save();
    ctx.translate(width / 2, height / 2);
    ctx.scale(camera.zoom, camera.zoom);
    ctx.translate(camera.x, camera.y);
    ctx.translate(-width / 2, -height / 2);

    const diamondHeight = (totalColumns + totalRows) * (tileH / 2);
    const originX = width / 2;
    const originY = (height - TILE_THICKNESS) / 2 - diamondHeight / 2;
    const viewConfig = { originX, originY, tileW, tileH };

    const vertices: Vec2[][] = [];
    for (let row = 0; row <= totalRows; row++) {
      const rowVerts: Vec2[] = [];
      for (let col = 0; col <= totalColumns; col++) {
        rowVerts.push(this.toIso(col, row, viewConfig));
      }
      vertices.push(rowVerts);
    }

    ctx.lineWidth = TILE_LINE_WIDTH;
    ctx.lineJoin = 'round';
    ctx.strokeStyle = STROKE_COLOR;

    for (let row = 0; row < totalRows; row++) {
      for (let col = 0; col < totalColumns; col++) {
        const tileParams: TileRenderParams = {
          context: ctx,
          tile: grid[row][col],
          surfaceTopLeft: vertices[row][col],
          surfaceTopRight: vertices[row][col + 1],
          surfaceBottomRight: vertices[row + 1][col + 1],
          surfaceBottomLeft: vertices[row + 1][col],
        };
        const wallParams: TileDepthParams = {
          context: ctx,
          thickness: TILE_THICKNESS,
          rowIndex: row,
          totalRows,
          columnIndex: col,
          totalColumns,
          surfaceTopRight: vertices[row][col + 1],
          surfaceBottomRight: vertices[row + 1][col + 1],
          surfaceBottomLeft: vertices[row + 1][col],
        };
        this.drawIsometricTile(tileParams, wallParams, config);
      }
    }

    const centerCol = (totalColumns - 1) / 2;
    const centerRow = (totalRows - 1) / 2;

    const positions = {
      north: { col: centerCol, row: -NAV_KEY_MARGIN },
      west:  { col: -NAV_KEY_MARGIN, row: centerRow },
      south: { col: centerCol, row: totalRows + NAV_KEY_MARGIN + NAV_KEY_OFFSET_EXTRA },
      east:  { col: totalColumns + NAV_KEY_MARGIN + NAV_KEY_OFFSET_EXTRA, row: centerRow },
    };

    this.drawDirectionKey(ctx, 'W', positions.north.col, positions.north.row, viewConfig);
    this.drawDirectionKey(ctx, 'A', positions.west.col,  positions.west.row,  viewConfig);
    this.drawDirectionKey(ctx, 'S', positions.south.col, positions.south.row, viewConfig);
    this.drawDirectionKey(ctx, 'D', positions.east.col,  positions.east.row,  viewConfig);
    ctx.restore();
  }


  // Method generated by Claude 4.6 Sonnet on March 29th 2026
  private drawDirectionKey(
    ctx: CanvasRenderingContext2D,
    keyChar: string,
    col: number,
    row: number,
    viewConfig: { originX: number; originY: number; tileW: number; tileH: number },
  ): void {

    const north = this.toIso(col, row, viewConfig);
    const east = this.toIso(col + 1, row, viewConfig);
    const west = this.toIso(col, row + 1, viewConfig);
    const size = 60;
    ctx.save();
    
    ctx.transform(
      (east.x - north.x) / size, (east.y - north.y) / size,
      (west.x - north.x) / size, (west.y - north.y) / size,
      north.x, north.y,
    );

    ctx.translate(-size / 2, -size / 2);
    ctx.fillStyle = 'rgba(255, 255, 255, 0.9)';
    ctx.strokeStyle = '#fff';
    ctx.lineWidth = 4;
    
    const r = 8;
    ctx.beginPath();
    ctx.moveTo(r, 0);
    ctx.lineTo(size - r, 0);
    ctx.quadraticCurveTo(size, 0, size, r);
    ctx.lineTo(size, size - r);
    ctx.quadraticCurveTo(size, size, size - r, size);
    ctx.lineTo(r, size);
    ctx.quadraticCurveTo(0, size, 0, size - r);
    ctx.lineTo(0, r);
    ctx.quadraticCurveTo(0, 0, r, 0);
    ctx.fill();
    ctx.stroke();

    ctx.fillStyle = '#3d3939ff';
    ctx.font = 'bold 36px Arial';
    ctx.textAlign = 'center';
    ctx.textBaseline = 'middle';
    ctx.fillText(keyChar, size / 2, size / 2 + 2);
    ctx.restore();
  }


  private drawTileDepth(params: TileDepthParams, colors: TileColorSet): void {
    const { context: ctx, rowIndex, columnIndex, totalRows, totalColumns, thickness,
      surfaceBottomLeft: west, surfaceBottomRight: south, surfaceTopRight: east } = params;
    const baseEast = { x: east.x, y: east.y + thickness };
    const baseSouth = { x: south.x, y: south.y + thickness };
    const baseWest = { x: west.x, y: west.y + thickness };

    // Left side
    if (rowIndex === totalRows - 1) {
      this.buildPolygonPath(ctx, [west, south, baseSouth, baseWest]);
      ctx.fillStyle = colors.left;
      ctx.fill();
      ctx.stroke();
    }
    
    // Right side
    if (columnIndex === totalColumns - 1) {
      this.buildPolygonPath(ctx, [south, east, baseEast, baseSouth]);
      ctx.fillStyle = colors.right;
      ctx.fill();
      ctx.stroke();
    }
  }

  private drawAssetsOnTile(params: TileRenderParams, col: number, row: number, config: RenderBoardConfig): void {
    const { context: ctx, tile, surfaceTopLeft: north, surfaceTopRight: east,
      surfaceBottomRight: south, surfaceBottomLeft: west } = params;

    const cx = (west.x + east.x) / 2;
    const cy = (north.y + south.y) / 2;
    const tileW = east.x - west.x;
    const tileH = south.y - north.y;
    const shadowParams = {
      yOffsetRatio: 0.05,
      wRatio: 0.4,
      hRatio: 0.1,
    };

    // Draws the floating animation if there is an item on the tile.
    if (tile.item != null) {
      const itemData = OBJECT_PLACEMENT_TOOL[tile.item];
      if (itemData?.image) {
        const itemImg = this.getImage(itemData.image);
        if (itemImg?.complete && itemImg.naturalWidth > 0) {
          const aspect = itemImg.naturalWidth / itemImg.naturalHeight;
          const imgW = tileW * RENDER_CONSTANTS.itemWidthRatio;
          const imgH = imgW / aspect;

          // Floating: sin of a constantly growing value returns a value [-1, 1].
          const floatOffset = Math.sin(Date.now() / RENDER_CONSTANTS.itemFloatSpeed) *
            (tileH * RENDER_CONSTANTS.itemFloatAmplitude) -
            (tileH * RENDER_CONSTANTS.itemFloatBaseOffset);

            const tileLeft = cx - imgW/2;
            const tileTop = cy - imgH/2;
          ctx.drawImage(itemImg, tileLeft, tileTop + floatOffset, imgW, imgH);
        }
      }
    }

    const playerAtTile = this.players.find((p) => {
      const pos = this.playerPositions[p.socketId];
      return pos?.x === col && pos?.y === row;
    });

    if (playerAtTile?.character?.avatar) {
      const playerImg = this.getImage(playerAtTile.character.avatar);
      if (playerImg?.complete && playerImg.naturalWidth > 0) {
        const aspect = playerImg.naturalWidth / playerImg.naturalHeight;
        const imgW = tileW * RENDER_CONSTANTS.playerWidthRatio;
        const imgH = imgW / aspect * RENDER_CONSTANTS.playerHeightAdjustment;
        const shadowY = cy + (tileH * shadowParams.yOffsetRatio);
        const radiusX = imgW * shadowParams.wRatio;
        const radiusY = imgH * shadowParams.hRatio;
        
        // Drawing shadow underneath avatar
        ctx.save();
        ctx.fillStyle = 'rgba(0, 0, 0, 0.4)';
        ctx.beginPath();
        ctx.ellipse(cx, shadowY, radiusX, radiusY, 0, 0, 2*Math.PI);
        ctx.fill();
        ctx.restore();

        const charX = cx - imgW / 2;
        const charY = cy - imgH + (tileH * RENDER_CONSTANTS.playerDepthOffset);

        // if the player is yourself, draws a glowing border
        if (playerAtTile.socketId === config.localPlayerSocketId) {
          ctx.save();
          ctx.shadowColor = '#00f2fe';
          ctx.shadowBlur = 12;

          // Stamping a solid non-blurry version onto the blurry border
          ctx.drawImage(playerImg, charX, charY, imgW, imgH);
          ctx.shadowBlur = 0;
          ctx.drawImage(playerImg, charX, charY, imgW, imgH);
          ctx.restore();
        } else {
          ctx.drawImage(playerImg, charX, charY, imgW, imgH);
        }
      }
    }
  }

  private drawIsometricTile(params: TileRenderParams, depthParams: TileDepthParams, config: RenderBoardConfig): void {
    const { context: ctx, tile, surfaceTopLeft: north, surfaceTopRight: east,
      surfaceBottomRight: south, surfaceBottomLeft: west } = params;
    const colors = TILE_COLORS[tile.type] || DEFAULT_COLOR;

    this.buildPolygonPath(ctx, [north, east, south, west]);
    ctx.fillStyle = colors.top;
    ctx.fill();

    // Warp tile texture onto the diamond surface
    const tileTool = TILE_TOOLS[tile.type];
    if (tileTool?.image) {
      const tileImg = this.getImage(tileTool.image);
      if (tileImg?.complete && tileImg.naturalWidth > 0) {
        ctx.save();
        ctx.clip();
        const iw = tileImg.naturalWidth;
        const ih = tileImg.naturalHeight;

        // Square image to diamond image transformation
        ctx.transform(
          (east.x - north.x) / iw, (east.y - north.y) / iw,
          (west.x - north.x) / ih, (west.y - north.y) / ih,
          north.x, north.y,
        );

        ctx.drawImage(tileImg, 0, 0);
        ctx.restore();
      }
    }

    const col = depthParams.columnIndex;
    const row = depthParams.rowIndex;
    const isReachable = config.reachableTiles?.some((t) => t.x === col && t.y === row);
    const isTeleportable = config.teleportableTiles?.some((t) => t.x === col && t.y === row);

    // Highlight of available tiles to move to
    if (isReachable || isTeleportable) {
      ctx.save();
      this.buildPolygonPath(ctx, [north, east, south, west]);
      ctx.fillStyle = isTeleportable ? 'rgba(0, 255, 255, 0.5)' : 'rgba(255, 255, 255, 0.4)';
      ctx.fill();
      ctx.restore();
    }

    ctx.stroke();
    this.drawTileDepth(depthParams, colors);
    this.drawAssetsOnTile(params, col, row, config);
  }


  private toIso(col: number, row: number, config: { originX: number; originY: number; tileW: number; tileH: number }): Vec2 {
    return {
      x: config.originX + (col - row) * (config.tileW / 2),
      y: config.originY + (col + row) * (config.tileH / 2),
    };
  }
}
