import { Vec2 } from '@common/vec2';
/* PORTCULLIS-RENDER.HELPER.TS - GENERATED BY CLAUDE 4.6 OPUS ON 04/04/2026 */

const TILE_LINE_WIDTH = 0.8;
const DOOR_ANIM_DURATION_MS = 350;

interface DoorAnimState {
  from: number;
  to: number;
  startMs: number;
}

const doorAnimMap = new Map<string, DoorAnimState>();

const EASE_HALF = 0.5;
const EASE_SCALE = 4;
const EASE_FLIP = -2;
const EASE_POWER = 3;
const EASE_DIVISOR = 2;

function easeInOut(t: number): number {
  return t < EASE_HALF
    ? EASE_SCALE * t * t * t
    : 1 - Math.pow(EASE_FLIP * t + EASE_DIVISOR, EASE_POWER) / EASE_DIVISOR;
}

// Helper to draw a single 3D polygonal face
function drawPoly(ctx: CanvasRenderingContext2D, points: Vec2[], fill: string, stroke = '#050402', lineWidth = TILE_LINE_WIDTH) {
  ctx.fillStyle = fill;
  ctx.beginPath();
  ctx.moveTo(points[0].x, points[0].y);
  for (let i = 1; i < points.length; i++) ctx.lineTo(points[i].x, points[i].y);
  ctx.closePath();
  ctx.fill();
  if (stroke) {
    ctx.strokeStyle = stroke;
    ctx.lineWidth = lineWidth;
    ctx.stroke();
  }
}

export function drawPortcullisBars(
    ctx: CanvasRenderingContext2D,
    corners: { north: Vec2; east: Vec2; south: Vec2; west: Vec2 },
    targetProgress: number,
    tileKey?: string,
  ): void {
  const { north, east, south, west } = corners;

  const now = Date.now();
  let progress = targetProgress;

  if (tileKey !== undefined) {
    const existing = doorAnimMap.get(tileKey);
    if (!existing) {
      doorAnimMap.set(tileKey, { from: targetProgress, to: targetProgress, startMs: now });
    } else if (existing.to !== targetProgress) {
      const animElapsed = now - existing.startMs;
      const animT = Math.min(animElapsed / DOOR_ANIM_DURATION_MS, 1);
      const currentProgress = existing.from + (existing.to - existing.from) * easeInOut(animT);
      doorAnimMap.set(tileKey, { from: currentProgress, to: targetProgress, startMs: now });
    }
    const state = doorAnimMap.get(tileKey);
    if (state) {
      const animElapsed = now - state.startMs;
      const animT = Math.min(animElapsed / DOOR_ANIM_DURATION_MS, 1);
      progress = state.from + (state.to - state.from) * easeInOut(animT);
    }
  }

  const BAR_COUNT = 4;
  const tileW = Math.max(east.x - west.x, 1);

  const BAR_HEIGHT_RATIO = 0.25;
  const BAR_WIDTH_RATIO = 0.06;
  const BAR_THICKNESS_RATIO = 0.04;
  const MIN_BAR_HEIGHT_RATIO = 0.025;

  const BAR_HEIGHT = tileW * (MIN_BAR_HEIGHT_RATIO + (BAR_HEIGHT_RATIO - MIN_BAR_HEIGHT_RATIO) * progress);
  const BAR_WIDTH = tileW * BAR_WIDTH_RATIO;
  const BAR_THICKNESS = tileW * BAR_THICKNESS_RATIO;

  const dxCol = east.x - north.x;
  const dyCol = east.y - north.y;
  const lenCol = Math.sqrt(dxCol * dxCol + dyCol * dyCol) || 1;
  const uCol = { x: dxCol / lenCol, y: dyCol / lenCol };

  const dxRow = west.x - north.x;
  const dyRow = west.y - north.y;
  const lenRow = Math.sqrt(dxRow * dxRow + dyRow * dyRow) || 1;
  const uRow = { x: dxRow / lenRow, y: dyRow / lenRow };

  const sides: { from: Vec2; to: Vec2; isCol: boolean }[] = [
    { from: north, to: west, isCol: false },
    { from: north, to: east, isCol: true },
    { from: west, to: south, isCol: true },
    { from: east, to: south, isCol: false },
  ];

  ctx.save();
  ctx.lineJoin = 'round';

  for (const { from, to, isCol } of sides) {
    const edgeDx = to.x - from.x;
    const edgeDy = to.y - from.y;

    for (let i = 1; i <= BAR_COUNT; i++) {
      const tBar = i / (BAR_COUNT + 1);
      const bx = from.x + edgeDx * tBar;
      const by = from.y + edgeDy * tBar;

      const sCol = isCol ? BAR_WIDTH : BAR_THICKNESS;
      const sRow = isCol ? BAR_THICKNESS : BAR_WIDTH;
      const hc = sCol / 2;
      const hr = sRow / 2;

      const p1 = { x: bx - uCol.x * hc - uRow.x * hr, y: by - uCol.y * hc - uRow.y * hr };
      const p2 = { x: bx + uCol.x * hc - uRow.x * hr, y: by + uCol.y * hc - uRow.y * hr };
      const p3 = { x: bx + uCol.x * hc + uRow.x * hr, y: by + uCol.y * hc + uRow.y * hr };
      const p4 = { x: bx - uCol.x * hc + uRow.x * hr, y: by - uCol.y * hc + uRow.y * hr };

      const cTop   = isCol ? '#8E8276' : '#83796F';
      const cLeft  = isCol ? '#766C63' : '#6B635B';
      const cRight = isCol ? '#554F48' : '#4D4741';

      drawPoly(ctx, [p4, p3, { x: p3.x, y: p3.y - BAR_HEIGHT }, { x: p4.x, y: p4.y - BAR_HEIGHT }], cLeft);
      drawPoly(ctx, [p3, p2, { x: p2.x, y: p2.y - BAR_HEIGHT }, { x: p3.x, y: p3.y - BAR_HEIGHT }], cRight);
      drawPoly(ctx, [
        { x: p1.x, y: p1.y - BAR_HEIGHT }, { x: p2.x, y: p2.y - BAR_HEIGHT },
        { x: p3.x, y: p3.y - BAR_HEIGHT }, { x: p4.x, y: p4.y - BAR_HEIGHT },
      ], cTop);
    }
  }

  ctx.restore();
}
