import { GameMode, TileItem } from './enums';
import { Vec2 } from './vec2';
import { Tile } from './tile'

export interface PlacedObject {
    type: TileItem;
    position: Vec2;
}

export interface Game {
    _id: string; // generated by mongodb
    name: string;
    description: string;
    size: { rows: number, cols: number };
    gameMode: GameMode;
    thumbnail: string;
    maxPlayers: number;
    grid: Tile[][];
    isVisible: boolean;
    createdAt: Date; // generated by mongodb
    updatedAt: Date; // generated by mongodb
}