import { GameMode, TileItem } from './enums';
import { GridSize } from './interfaces/grid-size';
import { Tile } from './tile';
import { Vec2 } from './vec2';

export interface PlacedObject {
    type: TileItem;
    position: Vec2;
}

export interface Game {
    _id: string; // generated by mongodb
    name: string;
    description: string;
    size: GridSize;
    gameMode: GameMode;
    thumbnail: string;
    maxPlayers: number;
    grid: Tile[][];
    isVisible: boolean;
    createdAt: Date; // generated by mongodb
    updatedAt: Date; // generated by mongodb
}
