import { Injectable } from '@angular/core';
import { Router } from '@angular/router';
import { Game } from '@app/interfaces/game';
import { CommunicationService } from '@app/services/communication/communication.service';
import { GameValidatorService } from '@app/services/game-validator/game-validator.service';
import { TileItemCounts } from '@app/services/map-setup.types';
import { MapSetupService } from '@app/services/map-setup/map-setup.service';
import { TileItemCountService } from '@app/services/tile-item-count/tile-item-count.service';
import html2canvas from 'html2canvas';

const THUMBNAIL_QUALITY = 0.85;
const THUMBNAIL_MAX_SIZE = 256;
export interface MapSetupInitResult {
  game: Game;
  mode: 'create' | 'edit';
  itemCounts: TileItemCounts;
}

@Injectable({ providedIn: 'root' })
export class MapSetupFacadeService {
  constructor(
    private readonly router: Router,
    private readonly communicationService: CommunicationService,
    private readonly gameValidator: GameValidatorService,
    private readonly mapSetupService: MapSetupService,
    private readonly tileItemCountService: TileItemCountService,
  ) {}

  initializeFromNavigation(): MapSetupInitResult {
    const state = history.state as { game?: Game; mode?: 'create' | 'edit' };

    if (!state?.game) {
      // Did not send a game object (did not come from our predifined path, fallback)
      this.router.navigate(['/games']);
    }

    const game = state.game as Game;
    const mode = state.mode ?? 'edit';

    this.mapSetupService.initializeGridIfEmpty(game);
    const itemCounts = this.tileItemCountService.createRequiredCounts(game);
    this.tileItemCountService.adjustCountsForExistingItems(game, itemCounts);

    return { game, mode, itemCounts };
  }

  navigateToAdmin(): void {
    this.router.navigate(['/admin']);
  }

  async saveGame(game: Game, initialMode: 'create' | 'edit'): Promise<void> {
    let mode = initialMode;


    try {
      const thumbnail = await this.captureThumbnail();
      game.thumbnail = thumbnail;
    } catch {
      alert("Problème d'enregistrement : la génération de l'image a échouée ");
      return;
    }

    const validation = this.gameValidator.validate(this.mapSetupService.buildValidationPayload(game));

    if (!validation.isValid) {
      alert(`Jeu invalide! :\n- ${validation.errors.join('\n- ')}`);
      return;
    }

    if (mode === 'edit') {
      this.communicationService.getAllGames().subscribe((allGames) => {
        const originalGame = allGames.find((currentGame) => currentGame._id === game._id);
        if (!originalGame) {
          mode = 'create';
        }

        const saveOperation = mode === 'create'
          ? this.communicationService.createGame(game)
          : this.communicationService.modifyGame(game);

        saveOperation.subscribe({
          next: () => {
            alert(`Jeu ${mode === 'create' ? 'créé' : 'sauvegardé'} avec succès !`);
            this.router.navigate(['/admin']);
          },
          error: () => {
            alert('Une erreur s\'est produite en enregistrant un jeu édité !');
          },
        });
      });
    } else {
      const saveOperation = this.communicationService.createGame(game);

      saveOperation.subscribe({
        next: () => {
          alert(`Partie créée avec succès !`);
          this.router.navigate(['/admin']);
        },
        error: () => {
          alert('Une erreur s\'est produite en enregistrant un nouveau jeu');
        },
      });
    }
  }

  // Generated by Claude Haiku 4.5 02/09/2026 (for the quality diminuation)
  private async captureThumbnail(): Promise<string> {
    const element = document.getElementById('thumbnail');
    if (!element) {
      throw new Error('image de prévisualisation est introuvable');
    }

    const canvas = await html2canvas(element, {
      scale: 2,
      useCORS: true,
      logging: false,
      backgroundColor: null,
      imageTimeout: 0,
    });

    const maxSize = THUMBNAIL_MAX_SIZE;
    const ctx = canvas.getContext('2d');
    if (!ctx) throw new Error("Impossible d'obtenir le contexte du canvas");

    const width = canvas.width > canvas.height ? maxSize : (canvas.width / canvas.height) * maxSize;
    const height = canvas.height > canvas.width ? maxSize : (canvas.height / canvas.width) * maxSize;

    const resizedCanvas = document.createElement('canvas');
    resizedCanvas.width = width;
    resizedCanvas.height = height;

    const resizedCtx = resizedCanvas.getContext('2d');
    if (!resizedCtx) throw new Error("Impossible d'obtenir le contexte du canvas redimensionné");

    resizedCtx.imageSmoothingEnabled = true;
    resizedCtx.imageSmoothingQuality = 'high';
    resizedCtx.drawImage(canvas, 0, 0, width, height);

    return resizedCanvas.toDataURL('image/jpeg', THUMBNAIL_QUALITY);
  }
}
