import { Tile } from './tile';


export interface Game {
    _id: string; // generated by mongodb
    name: string;
    description: string;
    size: { rows: number, cols: number };
    gameMode: string;
    thumbnail: string;
    maxPlayers: number;
    grid: Tile[][];
    isVisible: boolean;
    createdAt: Date; // generated by mongodb
    updatedAt: Date; // generated by mongodb
    __v: number; // generated by mongodb
}